language: android
sudo: required
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - build-tools-26.0.0
    - android-22
    - android-25
    - android-26
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - mksdcard -l sdcard 100M sdcard
  - emulator -avd test -no-audio -no-window -sdcard sdcard &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shel input keyevent 82 &

script:
  - ./gradlew ktlint build executeScreenshotTests -Pcom.android.threadPoolSize=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xms1024m -Xmx1024m" -Dorg.gradle.daemon=false
